name: foodcast_2022
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7.6
    - pip: 
        - cloudpickle==2.2.0
        - click==8.1.3
        - flake8==5.0.4
        - ipykernel==6.16.1
        - jupyter==1.0.0
        - jupytext==1.14.1
        - mlflow==1.30.0
        - nbformat==5.7.0
        - numpy==1.21.6
        - pandas==1.3.5
        - plotly==5.10.0
        - pytest==7.1.3
        - pytest-cov==4.0.0
        - python-dotenv==0.21.0
        - scikit-learn==1.0.2