name: foodcast_2022
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7.6
    - pip: 
        - cloudpickle==2.2.0
        - click==8.1.3
        - mlflow==1.30.0
        - nbformat==5.7.0
        - numpy==1.21.6
        - pandas==1.3.5
        - plotly==5.10.0
        - python-dotenv==0.21.0
        - scikit-learn==1.0.2